[package]
name = "rust-program"
version = "0.0.1"
edition = "2024"

[workspace]
members = ["crates/*", "protect-home-game", "my-ecs-rust", "my-macro"]

[dependencies]
my-macro = { path = "my-macro" }
engine_internal = { path = "crates/engine_internal" }
