[package]
name = "test-game"
version = "0.1.0"
edition = "2024"


[dependencies]
my-ecs-rust = { path = "../my-ecs-rust" }

pixels = "0.13"
winit = { version = "0.30", features = ["rwh_05"] }
rand = "0.8"
rust-embed = "8.0"
image = "0.24"
rodio = "0.20.1"
