[package]
name = "test-game"
version = "0.1.0"
edition = "2024"


[dependencies]
my-ecs-framework = { path = "../my-ecs-framework" }

pixels = "0.13"
winit = { version = "0.30", features = ["rwh_05"] }
ecs_rust = "0.0.4"
rand = "0.8"
