[package]
name = "engine_macro_utils"
version = "0.0.1"
edition = "2024"

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
toml_edit = { version = "0.23.2", default-features = false, features = [
  "parse",
] }
parking_lot = { version = "0.12" }
