[package]
name = "bevy_ecs_macros"
version = "0.0.1"
edition = "2024"

[dependencies]
syn = { version = "2.0.99", features = ["full", "extra-traits"] }
proc-macro2 = "1.0"
quote = "1.0"

[lib]
proc-macro = true
